[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 11.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraMono Nerd Font"
style = "Bold"

[font.italic]
family = "FiraMono Nerd Font"
style = "Regular"

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 4
