[colors]
transparent_background_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#FDF9E7"
yellow = "#fabd2f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#141617"
blue = "#659F92"
cyan = "#6BA163"
green = "#A9B665"
magenta = "#C86580"
red = "#EA6962"
white = "#D5C4A1"
yellow = "#A9B665"

[colors.normal]
black = "#282828"
blue = "#7DAEA3"
cyan = "#89B482"
green = "#A9B665"
magenta = "#D3869B"
red = "#EA696A"
white = "#FBF1C7"
yellow = "#D8A657"

[colors.primary]
background = "#282828"
bright_foreground = "#FDF9E7"
dim_foreground = "#D5C4A1"
foreground = "#FBF1C7"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
